<?php

/**
 *  Module converted to 6 by iStryker
 *  Module converted to 7 by iStryker
 *  Sponser by Themes 24/7  http://www.themes247.com & http://www.strykerenterprise.com
 */

/**
 * @file
 * Defines schema for email fields
 */

/**
 * Implements hook_field_schema().
 */
function cck_list_field_schema($field) {
  return array(
    'columns' => array(
      'list' => array(
        'type' => 'text',
        'not null' => FALSE,
      ),
    ),
  );
}